// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ThirdWheel.API.Data;

#nullable disable

namespace ThirdWheel.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424230650_AddSpamWarningUserIdIndex")]
    partial class AddSpamWarningUserIdIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ThirdWheel.API.Models.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlockerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BlockedUserId");

                    b.HasIndex("BlockerUserId", "BlockedUserId")
                        .IsUnique();

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("TargetChallengeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetOfferId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetPartnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TargetEventId");

                    b.HasIndex("TargetPartnerId");

                    b.ToTable("BusinessAuditLogs");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("BusinessCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a01"),
                            DisplayName = "Bar / Nightclub",
                            IsActive = true,
                            Key = "bar-nightclub",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a02"),
                            DisplayName = "Restaurant / Cafe",
                            IsActive = true,
                            Key = "restaurant-cafe",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a03"),
                            DisplayName = "Fitness / Wellness",
                            IsActive = true,
                            Key = "fitness-wellness",
                            SortOrder = 30
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a04"),
                            DisplayName = "Entertainment",
                            IsActive = true,
                            Key = "entertainment",
                            SortOrder = 40
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a05"),
                            DisplayName = "Retail",
                            IsActive = true,
                            Key = "retail",
                            SortOrder = 50
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a06"),
                            DisplayName = "Events & Experiences",
                            IsActive = true,
                            Key = "events-experiences",
                            SortOrder = 60
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a07"),
                            DisplayName = "Beauty & Spa",
                            IsActive = true,
                            Key = "beauty-spa",
                            SortOrder = 70
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a08"),
                            DisplayName = "Travel & Hospitality",
                            IsActive = true,
                            Key = "travel-hospitality",
                            SortOrder = 80
                        },
                        new
                        {
                            Id = new Guid("1d0c0a0b-3627-4f35-9208-cf0e13a89a09"),
                            DisplayName = "Other",
                            IsActive = true,
                            Key = "other",
                            SortOrder = 90
                        });
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalTicketUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId");

                    b.HasIndex("StartDate");

                    b.HasIndex("Status");

                    b.ToTable("BusinessEvents");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessEventImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEventId");

                    b.ToTable("BusinessEventImages");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessEventId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ClaimLimit")
                        .HasColumnType("integer");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OfferType")
                        .HasColumnType("integer");

                    b.Property<string>("RedemptionInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEventId");

                    b.HasIndex("Status");

                    b.ToTable("BusinessOffers");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BusinessPartners");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("BusinessPartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPartnerId")
                        .IsUnique();

                    b.ToTable("BusinessProfiles");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ChallengeResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventChallengeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventChallengeId", "Status");

                    b.HasIndex("UserId", "EventChallengeId")
                        .IsUnique();

                    b.ToTable("ChallengeResponses");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Couple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Couples");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.CouponClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessOfferId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClaimedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRedeemed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOfferId");

                    b.HasIndex("UserId", "BusinessOfferId")
                        .IsUnique();

                    b.ToTable("CouponClaims");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BannerUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventDate");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxWinners")
                        .HasColumnType("integer");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RewardDescription")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RewardType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEventId")
                        .IsUnique();

                    b.ToTable("EventChallenges");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId", "EventId")
                        .IsUnique();

                    b.ToTable("EventInterests");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEventId");

                    b.HasIndex("UserId", "BusinessEventId")
                        .IsUnique();

                    b.ToTable("EventLikes");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEventId");

                    b.HasIndex("UserId", "BusinessEventId")
                        .IsUnique();

                    b.ToTable("EventRegistrations");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventSave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BusinessEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BusinessEventId");

                    b.HasIndex("UserId", "BusinessEventId")
                        .IsUnique();

                    b.ToTable("EventSaves");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ImpressMePrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SenderContext")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SignalId")
                        .IsUnique();

                    b.ToTable("ImpressMePrompts");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ImpressMeResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MediaType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("SignalId")
                        .HasColumnType("uuid");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("SignalId")
                        .IsUnique();

                    b.ToTable("ImpressMeResponses");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ImpressMeSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Flow")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("ReceiverId", "CreatedAt");

                    b.HasIndex("SenderId", "CreatedAt");

                    b.HasIndex("SenderId", "ReceiverId", "Status");

                    b.ToTable("ImpressMeSignals");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FromCoupleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToCoupleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ToUserId");

                    b.HasIndex("FromUserId", "CreatedAt");

                    b.HasIndex("FromUserId", "ToUserId")
                        .IsUnique();

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Couple1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Couple2Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Couple1Id", "CreatedAt");

                    b.HasIndex("Couple2Id", "CreatedAt");

                    b.HasIndex("User1Id", "CreatedAt");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.HasIndex("User2Id", "CreatedAt");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("MatchId", "SentAt");

                    b.HasIndex("SenderId", "SentAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActorName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ActorPhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId", "CreatedAt");

                    b.HasIndex("RecipientId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReporterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReporterUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.RewardClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChallengeResponseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RewardCode")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RewardNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeResponseId");

                    b.HasIndex("EventChallengeId");

                    b.HasIndex("UserId", "EventChallengeId")
                        .IsUnique();

                    b.ToTable("RewardClaims");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.SavedProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SavedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SavedUserId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.HasIndex("UserId", "SavedUserId")
                        .IsUnique();

                    b.ToTable("SavedProfiles");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.SpamWarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("SpamWarnings");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeMax")
                        .HasColumnType("integer");

                    b.Property<int>("AgeMin")
                        .HasColumnType("integer");

                    b.Property<string>("AudioBioUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Children")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ComfortWithIntimacy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CoupleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drinking")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Drugs")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Ethnicity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FamilyPlans")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Height")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("InterestedIn")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("LookingFor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Marijuana")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Physique")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Politics")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("RadiusMiles")
                        .HasColumnType("integer");

                    b.Property<string>("RelationshipType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Religion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SexualPreference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Smoking")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("VideoBioUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Weight")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CoupleId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserInterests");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserRedFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRedFlags");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid?>("LastAttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("MethodKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MethodVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateJson")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MethodKey")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UserVerifications");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserVideos");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.VerificationAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MethodKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MethodVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestJson")
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationId", "StartedAt");

                    b.HasIndex("UserId", "MethodKey", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UserId", "MethodKey", "StartedAt");

                    b.ToTable("VerificationAttempts");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.VerificationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<int>("EventType")
                        .HasColumnType("integer");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("MethodKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VerificationId", "CreatedAt");

                    b.HasIndex("UserId", "MethodKey", "CreatedAt");

                    b.ToTable("VerificationEvents");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Block", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "BlockedUser")
                        .WithMany("BlocksReceived")
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "BlockerUser")
                        .WithMany("BlocksSent")
                        .HasForeignKey("BlockerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedUser");

                    b.Navigation("BlockerUser");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessEvent", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessPartner", "BusinessPartner")
                        .WithMany("Events")
                        .HasForeignKey("BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPartner");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessEventImage", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessEvent", "BusinessEvent")
                        .WithMany("Images")
                        .HasForeignKey("BusinessEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEvent");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessOffer", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessEvent", "BusinessEvent")
                        .WithMany("Offers")
                        .HasForeignKey("BusinessEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEvent");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessPartner", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessProfile", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessPartner", "BusinessPartner")
                        .WithOne("Profile")
                        .HasForeignKey("ThirdWheel.API.Models.BusinessProfile", "BusinessPartnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPartner");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ChallengeResponse", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.EventChallenge", "EventChallenge")
                        .WithMany("Responses")
                        .HasForeignKey("EventChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventChallenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.CouponClaim", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessOffer", "BusinessOffer")
                        .WithMany("Claims")
                        .HasForeignKey("BusinessOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessOffer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventChallenge", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessEvent", "BusinessEvent")
                        .WithOne("Challenge")
                        .HasForeignKey("ThirdWheel.API.Models.EventChallenge", "BusinessEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEvent");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventInterest", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.Event", "Event")
                        .WithMany("Interests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventLike", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessEvent", "BusinessEvent")
                        .WithMany("Likes")
                        .HasForeignKey("BusinessEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventRegistration", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessEvent", "BusinessEvent")
                        .WithMany("Registrations")
                        .HasForeignKey("BusinessEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventSave", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.BusinessEvent", "BusinessEvent")
                        .WithMany("Saves")
                        .HasForeignKey("BusinessEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ImpressMePrompt", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.ImpressMeSignal", "Signal")
                        .WithOne("Prompt")
                        .HasForeignKey("ThirdWheel.API.Models.ImpressMePrompt", "SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ImpressMeResponse", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.ImpressMeSignal", "Signal")
                        .WithOne("Response")
                        .HasForeignKey("ThirdWheel.API.Models.ImpressMeResponse", "SignalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Signal");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ImpressMeSignal", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Like", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "FromUser")
                        .WithMany("LikesSent")
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "ToUser")
                        .WithMany("LikesReceived")
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Message", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Report", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "ReporterUser")
                        .WithMany("ReportsSent")
                        .HasForeignKey("ReporterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReporterUser");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.RewardClaim", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.ChallengeResponse", "ChallengeResponse")
                        .WithMany()
                        .HasForeignKey("ChallengeResponseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.EventChallenge", "EventChallenge")
                        .WithMany("RewardClaims")
                        .HasForeignKey("EventChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChallengeResponse");

                    b.Navigation("EventChallenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.SavedProfile", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "SavedUser")
                        .WithMany()
                        .HasForeignKey("SavedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.SpamWarning", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.User", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.Couple", "Couple")
                        .WithMany("Members")
                        .HasForeignKey("CoupleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Couple");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserInterest", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany("Interests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserPhoto", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany("Photos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserRedFlag", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany("RedFlags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.UserVideo", b =>
                {
                    b.HasOne("ThirdWheel.API.Models.User", "User")
                        .WithMany("Videos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessEvent", b =>
                {
                    b.Navigation("Challenge");

                    b.Navigation("Images");

                    b.Navigation("Likes");

                    b.Navigation("Offers");

                    b.Navigation("Registrations");

                    b.Navigation("Saves");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessOffer", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.BusinessPartner", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Couple", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.Event", b =>
                {
                    b.Navigation("Interests");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.EventChallenge", b =>
                {
                    b.Navigation("Responses");

                    b.Navigation("RewardClaims");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.ImpressMeSignal", b =>
                {
                    b.Navigation("Prompt")
                        .IsRequired();

                    b.Navigation("Response");
                });

            modelBuilder.Entity("ThirdWheel.API.Models.User", b =>
                {
                    b.Navigation("BlocksReceived");

                    b.Navigation("BlocksSent");

                    b.Navigation("Interests");

                    b.Navigation("LikesReceived");

                    b.Navigation("LikesSent");

                    b.Navigation("Photos");

                    b.Navigation("RedFlags");

                    b.Navigation("ReportsSent");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
