using ThirdWheel.API.Models;

namespace ThirdWheel.API.Helpers;

public static class DefaultProfilePhoto
{
    public const string DataUrl =
        "data:image/png;base64," +
        "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAACiUlEQVR42u3dy00FMQwF0KmGCqmKOqiBKlghseYnsQPpfWYyvvZ5kveO71E2b5Js769vH2pu" +
        "bYYAgEEAoABQACgAFAAKAAWAAkABsLa+fg+XlvCaALgmdBiaAdgjfAgCAewZPAhhAI4MH4LiAFaED0FRACvDhwAAACoBOCN8CIoAODN8CAAAAAAATgNQIXwI" +
        "AAAAAAAA+K/HlycAJgD4DvraAiAdwA2hT8PQE8COwXeH0A/AgeF3RNALwILwuyHoAWBh8N0g5AM4MfwOCPL/CwBgMIAC4acjyAVQKPxkBJlfBBUMPxVB5jeB" +
        "AAwGUDj8RAR55wIAGH4yCIDBZwMDwk9DkHU6GIDh9wMAMPyGEABm3xEEAAAATAWQFH4SAjuAHQAAAAAAAAAAytbj4/NPJQH47RmAncJPBVAdwZYSfhKCv/oG" +
        "4M7g0wFUhbAlhd8BQDUEW1L4CQguXQMAN4bfBUAVBFta+JUR3LKO8QBuGVpFBPesA4BwBPeuYSyAewfXBcCZCLbk8Csg2HMdYwDsObSzIBy1BgACEBzZf3sA" +
        "Rw5vBYIV/QNQEMLKvtsCWDnEPTCc2S8AC2FU7KsdgIpDrl4AANADgDDrIgAAAAAAEP5YBAAAAAAAwh+LAAAAAAAAAAAAAAAAAAAAAAAAAABA+EMQ2AHsAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAEPgmEAAAAAAAAieDAAAAAAAgcD8AAABA4I4gAACAwD2BAAAAgbuCAQAAAu8FQODFEAi8GQQAABB4NxCCkPBj3w4W/uDXw4Xf" +
        "HEB3BNVmXRJARwhVZ1waQBcEledbHkA6guqzjQCQCCFlplEAEiCkzTISQEUIqTOMBlABQvrsPgHGOg1Y+orm5wAAAABJRU5ErkJggg==";

    public static UserPhoto Create(Guid userId) => new()
    {
        UserId = userId,
        Url = DataUrl,
        SortOrder = 0
    };
}
